//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGTransportManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoreSchool()
        {
            this.CoreBusRouteSchools = new HashSet<CoreBusRouteSchool>();
            this.NSGStudents = new HashSet<NSGStudent>();
        }
    
        public long SchoolID { get; set; }
        public string SchoolName { get; set; }
        public System.DateTime WinterTimingStart { get; set; }
        public System.DateTime WinterTimingEnd { get; set; }
        public System.TimeSpan WinterTimingFrom { get; set; }
        public System.TimeSpan WinterTimingTo { get; set; }
        public System.DateTime SummerTimingStart { get; set; }
        public System.DateTime SummerTimingEnd { get; set; }
        public System.TimeSpan SummerTimingFrom { get; set; }
        public System.TimeSpan SummerTimingTo { get; set; }
        public decimal DistanceFromGarage { get; set; }
        public string SchoolAddress { get; set; }
        public string AdminContactNumbers { get; set; }
        public int StateID { get; set; }
        public long CityID { get; set; }
        public bool IsActive { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoreBusRouteSchool> CoreBusRouteSchools { get; set; }
        public virtual CoreCity CoreCity { get; set; }
        public virtual CoreUser CoreUser { get; set; }
        public virtual CoreState CoreState { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NSGStudent> NSGStudents { get; set; }
    }
}
