//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGTransportManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreBus
    {
        public long BusID { get; set; }
        public string RegistrationNumber { get; set; }
        public int TotalSeatCount { get; set; }
        public int MaxPassengerAllowed { get; set; }
        public int KilometerRun { get; set; }
        public string DriverName { get; set; }
        public string DriverContactNumber { get; set; }
        public string CoDriverName { get; set; }
        public string CoDriverContactNumber { get; set; }
        public long BusRouteID { get; set; }
        public bool IsActive { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CoreBusRoute CoreBusRoute { get; set; }
        public virtual CoreUser CoreUser { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
    }
}
